apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  template:
    spec:
      initContainers:
        - name: init-dex-db
          volumeMounts:
            - name: init-dex-db
              readOnly: true
              mountPath: /etc/dex/init
          command: ["bash", "/etc/dex/init/init.sh"]
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: kotsadm-postgres
          - name: DEX_PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: kotsadm-dex-postgres
          image: kotsadm
          imagePullPolicy: IfNotPresent
      containers:
        - name: kotsadm
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: kotsadm-postgres # This secret is created in the migrations directory
                  key: uri
            - name: S3_BUCKET_NAME
              value: "shipbucket"
            - name: S3_ENDPOINT
              value: http://kotsadm-s3.default.svc.cluster.local:4569/
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"

